name: Rails Unit Tests

on: [push]

jobs:
  check-out-the-code:
    runs-on:  ubuntu-latest
    steps:
      - name: Export sidekiq credentials to local env
        run: |
          echo secrets.TEST_VAR=${{ secrets.TEST_VAR }}
          echo secrets.qa.BUNDLE_GEMS__CONTRIBSYS__COM=${{ qa.BUNDLE_GEMS__CONTRIBSYS__COM }}
          echo secrets.BUNDLE_GEMS__CONTRIBSYS__COM=${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}
          export BUNDLE_GEMS__CONTRIBSYS__COM=${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}
      # TODO: Add rest of the secrets
      # - name: "List directory: ls -ltr"
      #   run: |
      #     echo $(pwd)
      #     echo $(ls -ltr)
      # - name: Create env file for bertha-pumpngo
      #   run: |
      #     echo $(pwd)
      #     touch bertha-pumpngo/secret.env
      #     echo BERTHA_BACKEND_HOST= >> bertha-pumpngo/secret.env
      # # TODO: Add rest of the secrets
      # - name: Replace bertha-pumpngo path in docker-compose.ci.yml
      #   run: |
      #     sed -i 's/context: ..\/bertha-pumpngo/context: bertha-pumpngo/' docker-compose.ci.yml
      #     sed -i 's/env_file: ..\/bertha-pumpngo/env_file: bertha-pumpngo/' docker-compose.ci.yml
      # - name: Build images
      #   run: docker compose -f docker-compose.ci.yml build
      # - name: Run container
      #   run: docker compose -f docker-compose.ci.yml up
      # - name: Run tests
      #   run: docker compose run unit-test
