name: Workflow for pull requests
on: [push]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-out-the-code:
    runs-on:  ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build images
        run: docker compose build
      - name: Run container
        run: docker compose up
      - name: Run tests
        run: docker compose run unit-test
